name: CheckPython

on: [push, pull_request]

jobs:
  clean-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
      - uses: nkarasiak/ruff-action@v2
      - uses: jakebailey/pyright-action@v2
